name: dmbsaxboyz
favicon: null
layout_spectrum: 0.49959562299773097
typography_spectrum: 0.1820746350567788
title: Testing Grounds
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.06550618843175471
  lightness: 0.041576185496523976
  saturation: 0.5344420452602208
  rhythmicContrast: 0.8170303022488952
purpose: []
